### ISSUE TITLE
Struggling to get template up and running

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/Fluvial-Geomorphology#1]
Hey @MattReimer 
I just tried to create a new website repo (in my Restoration-USU actually). I couldn't get it to work. So I tried putting it over in Riverscapes (wasn't sure if I needed to be over here for theme to work)? Anyhow, it makes more sense for this to live over in Restoration-USU, but can you see what I'm doing wrong. I just did what I did previously...
1. Copied from https://github.com/Riverscapes/riverscapes-jekyll-theme/docs into root. 
2. Edited YML
3. Pushed up... 

Thoughts? Sorry for incompetence...  I do it just infrequently enough to screw it up. 

Thanks,
Joe

**Comment by MattReimer** [comment]
Hey @joewheaton. It was just a couple of small things in the end. 

When you use a github.io address your site sits in a subfolder so you need `baseurl`:

like so:

```yml
# Final root url of the site. No ending slash. No subdirectory
url: https://riverscapes.github.io
# If the site is in a subdirectory url you should do it like this: "/subdirectory". Otherwise ""
baseurl: "/Fluvial-Geomorphology"
```

Also remote theme was set to the debug version:

```yml
# remote_theme: Riverscapes/riverscapes-jekyll-theme@dev FOR DEBUGGING ONLY
remote_theme: Riverscapes/riverscapes-jekyll-theme
```
